### ISSUE TITLE
Territory War command is hanging

### ISSUE THREAD

**Issue by DRSisco** [jmiln/SWGoHBot#126]
### Issue description

Triggering a `/territorywar` command with two ally codes, hangs after the UI presents: 
> Found guilds for both ally codes, getting stats...

### Priority this issue should have

Low (slightly annoying)

**Comment by jmiln** [comment]
Looks like I'm having the same issue, so will take a look when I get the chance. Thanks for letting me know

**Comment by jmiln** [comment]
Hey, looks like mine came through and updated 4min later, so sorta working but really slow...

**Comment by DRSisco** [comment]
Okay, mine went through about 4 minutes later too. Hmmm, maybe when triggered really quickly after the war starts might have issues? 
Do you have logs to see if there are any memory issues? I doubt there is much to be done here, beyond queuing the requests or something.

**Comment by jmiln** [comment]
Looking into it more now, it doesn't seem to be hanging on pulling the player's data like I'd assumed, so I'm confused but digging around. I'll let ya know when I've got something figured out

**Comment by jmiln** [comment]
Turns out when I moved the db info over. It didn't copy the indexes, so the db lookup/ inserts were taking way longer than expected. I've updated that and it seems to be running way faster now

**Comment by DRSisco** [comment]
Thank you!
