### ISSUE TITLE
Unmet Dependencies

### ISSUE THREAD

**Issue by loudambiance** [jmiln/SWGoHBot#15]
package.json seems to have an incomplete listing of dependencies. When I install, I am left with the following unmet dependencies that I have to manually install:

UNMET PEER DEPENDENCY bufferutil@^3.0.2
UNMET PEER DEPENDENCY erlpack@hammerandchisel/erlpack
UNMET PEER DEPENDENCY libsodium-wrappers@^0.5.4
UNMET PEER DEPENDENCY node-opus@^0.2.6
UNMET PEER DEPENDENCY opusscript@^0.0.3
UNMET PEER DEPENDENCY sodium@^2.0.1
UNMET PEER DEPENDENCY uws@^0.14.5

System Info:
I am attempting to set this up on Fedora 25 with the most recent NPM and NodeJS packages from the Fedora repo:
npm-3.10.10-1.6.11.2.1.fc25.x86_64
nodejs-6.11.2-1.fc25.x86_64

**Comment by loudambiance** [comment]
I did not create a pull request adding these dependencies, because I did not want to presume to know exactly what versions should be included.

**Comment by jmiln** [comment]
It requires node 8+, as it says in the README.... Yes the README is outdated, as I generally assume people will use the main bot and I forget, but earlier versions of node will not work

**Comment by loudambiance** [comment]
Totally missed that, even when I forked it and fixed the git pull command. My apologies :-\

**Comment by loudambiance** [comment]
I uninstalled Node, and installed directly from NodeJS repo instead of Fedora repo, bringing me up to version 8.5. The same unmet deps occurred. I purged the node_modules folder and reran npm install after reinstalling.

**Comment by jmiln** [comment]
Are they errors or warnings? Those may just be the depenancies needed for voice chat which I don't use. If they're warnings, you can ignore them. I don't recognize sodium, but the others are for that I believe.

**Comment by jmiln** [comment]
Just confirmed it with the d.js support server, those are all optional unless using the bot for voice/ music bot
