### ISSUE TITLE
;reg remove not working

### ISSUE THREAD

**Issue by eris3d** [jmiln/SWGoHBot#58]
Hi there.
So I have your bot on a server and I kicked someone from it and now I can't ;reg remove that guy in any way. I tried with Discord @Name#XXXX, Name#XXXX, #XXXX, XXXX but nothing seems to be working.
Why not add ;reg remove <ally-code> directly so we can remove them even if they are not present.
Is there a way to remove him now?
Thanks!
Good work, bot is great.

**Comment by jmiln** [comment]
Not an issue, use ;reg update.

**Comment by eris3d** [comment]
That only updates my profile. I want to remove the profile of someone who
is not on the server anymore but still appears in the stats (like ;search)

mar., 10 iul. 2018, 17:02 Jeff <notifications@github.com> a scris:

**Comment by jmiln** [comment]
Right, so ;register update <user>, it will update their synced data, and show them not in your guild anymore

**Comment by eris3d** [comment]
Sorry, I might have some problems understanding you...

*Movan Lipost*-azi la 11:29
;reg update
*SWGoHBot*BOT-azi la 11:29
Profile updated for Movan Lipost.(editat)

How is that helping me to remove someone who is not on the server anymore?

I can't just use ;reg update @Nickname because he is not on the server...


Pe 15 iul. 2018 06:41, "Jeff" <notifications@github.com> a scris:

Right, so ;register update , it will update their synced data, and show
them not in your guild anymore

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jmiln/SWGoHBot/issues/58#issuecomment-405065054>, or mute
the thread

**Comment by jmiln** [comment]
;reg remove only unlinks their ally code from their discord ID in the bot's database. The data is still synced.
Either go find an old message, and get their discord ID, or run ";register update me -g" to re-update your entire guild and that will do what you need

**Comment by eris3d** [comment]
Thanks a lot, that solved my problem and even did something else, a good thing: added all the profiles in the guild, even though they were not present on Discord :+1: 
You have some hidden & interesting stuff on your bot, nice work!
