### ISSUE TITLE
";event view --page X" not working

### ISSUE THREAD

**Issue by eris3d** [jmiln/SWGoHBot#62]
#### Issue Details:
I try to see page 2 of my events with ;event view command and it's not working. I saw that ;event view --min works, but when I use --page I get the reply in the screenshots.

Thanks.

#### Supporting Information:

![page](https://user-images.githubusercontent.com/40557360/42657904-5c3231e4-862c-11e8-8e97-a0bd1c0c17d6.PNG)
![page 2](https://user-images.githubusercontent.com/40557360/42657903-5c13aec2-862c-11e8-868e-f8003842608a.PNG)

PS: Great work with the bot, dude! GG!

**Comment by jmiln** [comment]
Use -p instead of page for now, I'll fix it later today

**Comment by eris3d** [comment]
Super fast. Thank you!
